trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self

  - task: TerraformInstaller@0
    displayName: Install Terraform
    inputs:
      terraformVersion: 'latest'

  - task: AzureCLI@2
    displayName: Terraform Init & Apply
    inputs:
      azureSubscription: cloudaura-azure-connection
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        curl -LO https://github.com/Azure/kubelogin/releases/download/v0.2.19/kubelogin-linux-amd64.zip
        unzip kubelogin-linux-amd64.zip
        sudo mv bin/linux_amd64/kubelogin /usr/local/bin/
        terraform init
        terraform apply -auto-approve \
          -var="cluster_admin_object_id=$(cluster_admin_object_id)"